### ISSUE TITLE
Memoising JSX

### ISSUE THREAD

**Issue by oliverjam** [fac19/week10-gv#23]
https://github.com/fac19/week10-gv/blob/307930b83012ed4985dccfd772280ef4045ea00a/src/components/App.js#L18-L32

I'm confused here—why are you memoising the return value of your component?

Since you've put every state value inside the dependencies array the memoised function will re-run whenever any state update occurs, which is the default behaviour of a React component without memoisation. So this is probably not necessary.

**Comment by VatsKan** [comment]
thanks didn't really know what we were doing... :D

**Comment by oliverjam** [comment]
Out of curiosity where did you find out about `useMemo`, and what were you trying to achieve?

**Comment by VatsKan** [comment]
we were originally returning a nested ternary, and dominic suggested to put it in a function inside a useMemo instead...wasn't really sure what it did though :S
